#!/usr/bin/env python3

import os
import subprocess
import sys


current_dir = os.path.dirname(os.path.abspath(__file__))


if not os.path.exists(f"{current_dir}/XlibNoSHM.so"):
    print("XlibNoSHM.so not found. Compiling")
    subprocess.check_call([
        "cc",
        "-shared",
        "-o",
        f"{current_dir}/XlibNoSHM.so",
        f"{current_dir}/XlibNoSHM.c",
   ])
    print("Compilation complete")

# LD_PRELOAD="libdl.so $CURDIR/XlibNoSHM.so" $@

arguments = list(sys.argv)[1:]

print(f"Running without MIT-SHM: {arguments}")
environment = dict(os.environ)
environment["LD_PRELOAD"] = f"libdl.so {current_dir}/XlibNoSHM.so"

subprocess.check_call(
    arguments,
    env=environment
)

